# Generated by Django 4.0.3 on 2022-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_api', '0003_student_data_standard_alter_student_data_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_csv', models.FileField(blank=True, null=True, upload_to='imgs')),
            ],
        ),
    ]
